<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library
[
    <!ELEMENT library (book+)>
    <!ELEMENT book (title, author, year, genre, publisher, isbn, price, ratings?, comments?, tags?)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (name, birthplace)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT birthplace (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT genre (#PCDATA)>
    <!ELEMENT publisher (name, location)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT location (#PCDATA)>
    <!ELEMENT isbn (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ATTLIST price currency CDATA>
    <!ELEMENT ratings (rating*)>
    <!ELEMENT rating EMPTY>
    <!ATTLIST rating score CDATA>
    <!ELEMENT comments (comment*)>
    <!ELEMENT comment (#PCDATA)>
    <!ELEMENT tags (tag*)>
    <!ELEMENT tag (#PCDATA)>
]>

<?xml version="1.0" encoding="UTF-8"?>

<library>
    <book>
        <title>The Great Gatsby</title>
        <author>
            <name>F. Scott Fitzgerald</name>
            <birthplace>St. Paul, Minnesota, USA</birthplace>
        </author>
        <year>1925</year>
        <genre>Fiction</genre>
        <publisher>
            <name>Scribner</name>
            <location>New York</location>
        </publisher>
        <isbn>9780743273565</isbn>
        <price currency="USD">10.99</price>
        <ratings>
            <rating score="4.5" />
            <rating score="3.8" />
            <rating score="4.2" />
        </ratings>
        <comments>
            <comment>Great book!</comment>
            <comment>Highly recommended.</comment>
        </comments>
        <tags>
            <tag>classic</tag>
            <tag>American literature</tag>
        </tags>
    </book>
</library>