=== danielelol155/1-DAW/HTML/XML/productos-schema.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!DOCTYPE [
<!ELEMENT  productos (producto)+>
<!ELEMENT producto (nombre,(precio|precioconiva),categoria+,proveedor)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT precioconiva (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT proveedor (#PCDATA)>
]>

=== danielelol155/1-DAW/HTML/XML/productos.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!-- si la dtd es externa se pone standalone no, si no es externa se pone la standalone yes    -->
<!DOCTYPE productos SYSTEM "productos-schema.dtd">

<productos>
	<producto>
		<nombre>Teclado QWERTY</nombre>
		<precio>6.00</precio>
		<categoria>Teclados</categoria>
		<proveedor>Huawei</proveedor>
	</producto>
	<producto>
		<nombre>Ratón con cable</nombre>
		<precioconiva>5.00</precioconiva>
		<categoria>Ratones</categoria>
		<proveedor/>
	</producto>
	<producto>
		<nombre>Cañón proyector</nombre>
		<precio>500</precio>
		<categoria>Proyectores</categoria>
		<proveedor>Benq</proveedor>
	</producto>
	
</productos>
